set(sources
	src/about_qt.cpp
	src/about_qt.h
	src/about_qt.ui
	src/buildinfo.c
	src/buildinfo.h
	src/CmdQueue.cpp
	src/CmdQueue.h
	src/common.h
	src/config_qt.cpp
	src/config_qt.h
	src/config_qt.ui
	src/ConfigModel.cpp
	src/ConfigModel.h
	src/ExpandableSection.cpp
	src/ExpandableSection.h
	src/ExpandableSection.ui
	src/HighResClock.cpp
	src/HighResClock.h
	src/inputfile.h
	src/inputfileffmpeg.cpp
	src/main.cpp
	src/main.h
	src/peakmeter.h
	src/plugin.cpp
	src/plugin.h
	src/qtres.qrc
	src/SampleBuffer.cpp
	src/SampleBuffer.h
	src/SampleProducer.h
	src/SampleProducerThread.cpp
	src/SampleProducerThread.h
	src/samples.cpp
	src/samples.h
	src/SampleSource.h
	src/SampleVisualizerThread.cpp
	src/SampleVisualizerThread.h
	src/SoundButton.cpp
	src/SoundButton.h
	src/SoundInfo.cpp
	src/SoundInfo.h
	src/soundsettings_qt.cpp
	src/soundsettings_qt.h
	src/soundsettings_qt.ui
	src/soundview_qt.cpp
	src/soundview_qt.h
	src/SpeechBubble.cpp
	src/SpeechBubble.h
	src/TalkStateManager.cpp
	src/TalkStateManager.h
	src/ts3log.cpp
	src/ts3log.h
	src/UpdateChecker.cpp
	src/UpdateChecker.h
	src/updater.ui
	src/updater_qt.cpp
	src/updater_qt.h
	src/updater_qt.ui
)
