set(sources
	src/About.cpp
	src/About.h
	src/About.ui
	src/buildinfo.c
	src/buildinfo.h
	src/CmdQueue.cpp
	src/CmdQueue.h
	src/common.h
	src/Config.cpp
	src/Config.h
	src/Config.ui
	src/ConfigModel.cpp
	src/ConfigModel.h
	src/ExpandableSection.cpp
	src/ExpandableSection.h
	src/ExpandableSection.ui
	src/HighResClock.cpp
	src/HighResClock.h
	src/inputfile.h
	src/inputfileffmpeg.cpp
	src/main.cpp
	src/main.h
	src/peakmeter.h
	src/plugin.cpp
	src/plugin.h
	src/qtres.qrc
	src/SampleBuffer.cpp
	src/SampleBuffer.h
	src/SampleProducer.h
	src/SampleProducerThread.cpp
	src/SampleProducerThread.h
	src/samples.cpp
	src/samples.h
	src/SampleSource.h
	src/SampleVisualizerThread.cpp
	src/SampleVisualizerThread.h
	src/SoundButton.cpp
	src/SoundButton.h
	src/SoundInfo.cpp
	src/SoundInfo.h
	src/SoundSettings.cpp
	src/SoundSettings.h
	src/SoundSettings.ui
	src/SoundView.cpp
	src/SoundView.h
	src/SpeechBubble.cpp
	src/SpeechBubble.h
	src/TalkStateManager.cpp
	src/TalkStateManager.h
	src/ts3log.cpp
	src/ts3log.h
	src/UpdateChecker.cpp
	src/UpdateChecker.h
	src/updater.ui
	src/UpdaterWindow.cpp
	src/UpdaterWindow.h
	src/UpdaterWindow.ui
)
